### ISSUE TITLE
Types are missing for the newer version of logysia

### ISSUE THREAD

**Issue by vishwa5854** [tristanisham/logysia#17] opened 2024-06-21 04:47 UTC
Since the newer version just ships the dist folder, VSCode's TS language server complains 
`Could not find a declaration file for module '@grotto/logysia'. '/***/node_modules/@grotto/logysia/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/grotto__logysia` if it exists or add a new declaration (.d.ts) file containing `declare module '@grotto/logysia';`ts(7016)`

**Comment by vishwa5854** [comment] 2024-06-21 04:59
I saw that the release package.json has a `types` tag but the specified file `dist/index.d.ts` doesn't exist in the release. Please fix it

**Comment by johnsilver94** [comment] 2024-08-12 16:05
I resolved this problem in this [PR](https://github.com/tristanisham/logysia/pull/18l);
There was a simple error caused by tsconfig.json;

**Comment by iamkoby** [comment] 2024-09-07 04:42
so... can you approve the PR?  @tristanisham

**Comment by brenc** [comment] 2024-11-22 15:30
This makes logysia unusable for me.

**Comment by johnsilver94** [comment] 2024-11-22 18:54
> This makes logysia unusable for me.

@brenc I think this is because my PR was merged into the codebase, but a new version hasn't been released yet.

**Comment by tristanisham** [comment] 2024-11-22 21:11
Sorry y'all. Was distracted by other projects. Should be merged and up to date now.

**Closed as completed by tristanisham** 2024-11-22 21:11 UTC
